
spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: http://host.docker.internal:9092
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    hostname: host.docker.internal
server:
  port: 8081

product-price-service:
  service-id: product-price-service
