spring:
  application:
    name: product-price-service
#   redis:
#     host: host.docker.internal
eureka:
  instance:
    prefer-ip-address: true
#   client:
#     service-url:
#       defaultZone: http://host.docker.internal:8761/eureka/

server:
  port: 8082
