spring:
  application:
    name: product-price-service
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  redis:
    host: http://host.docker.internal:6379
server:
  port: 8082
